// Generated by CoffeeScript 1.4.0
(function() {
  var MyUser, UserSchema, addUser, db;

  db = require('../lib/db');

  UserSchema = new db.Schema({
    username: {
      type: String,
      unique: true
    },
    password: String
  });

  MyUser = db.mongoose.model('User', UserSchema);

  module.exports.addUser = addUser;

  addUser = function(username, password, callback) {
    var instance;
    instance = new MyUser();
    instance.username = username;
    instance.password = password;
    instance.save(function(err) {
      if (err) {
        callback(err);
      } else {
        callback(null, instance);
      }
    });
  };

}).call(this);
